### ISSUE TITLE
Broken paths

### ISSUE THREAD

**Issue by jtrotsky** [poynt/python-sample#4]
It seems that there are some broken paths that prevent the app from running first time.
It seems as if PoyntAPI.py was moved a level lower into `src/` which broke these references.

**Main file**
https://github.com/poynt/python-sample/blob/master/src/PoyntAPI.py#L658

This needs to be `../config/poynt.ini`

**Config file**
https://github.com/poynt/python-sample/blob/master/config/poynt.ini#L12

Lines 12,13,14 all need to be (prob applies to other lines too).
`../keys/*`

**Comment by ppalavilli** [comment]
Hi - thanks for reporting it. If you run the sample from the root folder as specified in the README file it would work. 

$ ./src/PoyntAPI.py

cheers,
Praveen

**Comment by jtrotsky** [comment]
My mistake, works fine that way.

**Comment by ppalavilli** [comment]
just FYI - @dsnatochy modified code to run from any directory: https://github.com/poynt/python-sample/pull/6
